from app.main_v015 import app
from app.enigma_rating import router as enigma_rating_router
from app.enigma_rating_v2 import router as enigma_rating_v2_router
from app.enigma_rating_v2_routes import router as enigma_rating_v2_fixture_router
from app.enigma_rating_v2_evaluation import router as enigma_rating_v2_evaluation_router
from app.enigma_rating_v2_evaluation_chronology import install_evaluation_v1_xg_chronology_fix
from app.enigma_rating_v2_tuning import router as enigma_rating_v2_tuning_router
from app.enigma_rating_v2_tuning_refinement import router as enigma_rating_v2_tuning_refinement_router
from app.enigma_rating_v2_frozen_params import router as enigma_rating_v2_frozen_params_router
from app.enigma_rating_v2_confirmation_holdout import (
    install_confirmation_holdout_startup,
    router as enigma_rating_v2_confirmation_holdout_router,
)
from app.enigma_rating_v2_confirmation_hook import install_confirmation_holdout_j1_hook
from app.daily_operations_business_date_fix import install_daily_operations_business_date_fix
from app.forward_test_report_v2 import router as forward_test_report_v2_router
from app.forward_test_report_v3 import router as forward_test_report_v3_router
from app.j1_work_api import router as j1_work_router
from app.performance_observatory import router as performance_observatory_router
from app.odds_window_clv import router as odds_window_clv_router
from app.dashboard_confirmation_holdout_v1 import router as dashboard_confirmation_holdout_router
from app.dashboard_j1_watchlist_patch import install_dashboard_j1_watchlist_patch
from app.dashboard_match_center_v3_5m import router as dashboard_match_center_v3_router
from app.dashboard_match_center_alias import router as dashboard_match_center_alias_router
from app.daily_analysis_report import router as daily_analysis_report_router
from app.sportmonks_coverage_audit import router as sportmonks_coverage_audit_router
from app.sportmonks_enrichment_provider import router as sportmonks_enrichment_provider_router
from app.xg_historical_backfill import router as xg_historical_backfill_router
from app.xg_backfill_startup import install_xg_backfill_startup

# Current production wrapper. Routers are registered in main_v015 for backward
# compatibility with Render services whose start command has not been updated.
app.version = "0.53.8"
install_daily_operations_business_date_fix()
install_evaluation_v1_xg_chronology_fix()
install_confirmation_holdout_j1_hook()
install_dashboard_j1_watchlist_patch()
install_confirmation_holdout_startup(app)
app.include_router(enigma_rating_router)
app.include_router(enigma_rating_v2_router)
app.include_router(enigma_rating_v2_fixture_router)
app.include_router(enigma_rating_v2_evaluation_router)
app.include_router(enigma_rating_v2_tuning_router)
app.include_router(enigma_rating_v2_tuning_refinement_router)
app.include_router(enigma_rating_v2_frozen_params_router)
app.include_router(enigma_rating_v2_confirmation_holdout_router)
app.include_router(performance_observatory_router)
app.include_router(odds_window_clv_router)
app.include_router(forward_test_report_v2_router)
app.include_router(forward_test_report_v3_router)
app.include_router(j1_work_router)
app.include_router(dashboard_confirmation_holdout_router)
app.include_router(dashboard_match_center_v3_router)
app.include_router(dashboard_match_center_alias_router)
app.include_router(daily_analysis_report_router)
app.include_router(sportmonks_coverage_audit_router)
app.include_router(sportmonks_enrichment_provider_router)
app.include_router(xg_historical_backfill_router)
install_xg_backfill_startup(app)
