create table if not exists fixtures (
  id bigint generated by default as identity primary key,
  sportmonks_id bigint not null unique,
  league_name varchar(160),
  home_team varchar(160) not null,
  away_team varchar(160) not null,
  starts_at timestamptz not null,
  status varchar(50),
  created_at timestamptz not null default now()
);
create index if not exists ix_fixtures_starts_at on fixtures(starts_at);

create table if not exists predictions (
  id bigint generated by default as identity primary key,
  fixture_id bigint not null references fixtures(id),
  window varchar(30) not null,
  model_version varchar(30) not null,
  p_home numeric(8,6) not null check (p_home between 0 and 1),
  p_draw numeric(8,6) not null check (p_draw between 0 and 1),
  p_away numeric(8,6) not null check (p_away between 0 and 1),
  generated_at timestamptz not null default now(),
  unique(fixture_id, window, model_version),
  check (abs((p_home + p_draw + p_away) - 1) < 0.00001)
);

create table if not exists odds_snapshots (
  id bigint generated by default as identity primary key,
  fixture_id bigint not null references fixtures(id),
  bookmaker varchar(120) not null,
  market varchar(80) not null,
  selection varchar(120) not null,
  odd numeric(10,4) not null check (odd > 1),
  source varchar(80) not null default 'sportmonks',
  source_updated_at timestamptz,
  fetched_at timestamptz not null default now(),
  window varchar(30)
);
create index if not exists ix_odds_fixture_time on odds_snapshots(fixture_id, fetched_at);
create index if not exists ix_odds_market on odds_snapshots(market, bookmaker);
