create table if not exists fixture_data_snapshots (
  id bigint generated by default as identity primary key,
  fixture_id bigint not null references fixtures(id),
  source varchar(80) not null default 'sportmonks',
  lineups jsonb,
  statistics jsonb,
  xg jsonb,
  fetched_at timestamptz not null default now()
);

create index if not exists ix_fixture_data_fixture_time
on fixture_data_snapshots(fixture_id, fetched_at);
